### ISSUE TITLE
Not working with touch devices?

### ISSUE THREAD

**Issue by cruonline** [rlemaigre/Easy-DnD#3]
I was just evaluating dnd support for my app and have found your solution.
I love it so far, but noticed it doesn't work at all with touch.
Shouldn't be much hassle to fix this, by adding touchstart, touchmove and touchstop events handling.

**Comment by rlemaigre** [comment]
Hello,

Thank you for your interest.

I totally forgot about touch devices when I was coding this. But it is something I'll have to do eventually because it's meant to be used some day in a webapp I work on that will have to support touch devices.

It's not so simple to do though, because I used mouseenter and mouseleave, and I'm not sure there is an equivalent for that on touch devices :-( . I believe I could get away with using mousemove / touchemove events instead.

**Comment by jaronwanderley** [comment]
So just like @cruonline, I was evaluating the use Easy-DnD with my web application, because it's just the Vue way of doing it ... ❤️
But I really need touch support and, as @rlemaigre said there are no touch events that replace mouseenter and mouseleave, so I made a workaround with custom events. I hope it will be helpful ...

@rlemaigre, see if this can be useful
https://codepen.io/JaronWanderley/pen/OJVaYxb

**Comment by jaronwanderley** [comment]
If you try this pen on Chrome DevTools, to test the touch events, please reload the page to make sure that the main device pointer is touchscreen, because on touch devices, browsers emit the event mouseenter on click.... thats a very weird behaivor, but I made another workaround about that, so I verify on window load, with media query, if the main pointer is touch... and on my method I ignore mouseenter events se is touch.

**Comment by rlemaigre** [comment]
Version 1.4.0 uses only mousemove instead of mouseenter and mouseleave. Now it should be really easy to support touch devices.

**Comment by Heniker** [comment]
I am not sure if that's what you've been looking for, but there are PointerEnter and PointerLeave events, which should work on mobile devices.
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events
