### ISSUE TITLE
Recursive drop zone not working as expected

### ISSUE THREAD

**Issue by Armaldio** [rlemaigre/Easy-DnD#7]
![preview](https://i.imgur.com/jFarH3t.gif)

First element is a droplist, then I add a button to it, then a container (which is also a droplist) then a button inside the container
It all works fine
Then I try to put the button inside the container, outside of it

1. It crash
![image](https://user-images.githubusercontent.com/3089715/78114497-aa597480-7401-11ea-925c-59651499a214.png)
2. Before crashing, it doesn't seems to detect dropable zones as I have css coloring drop-allow and drop-disallow

Any hints on this ?

**Comment by rlemaigre** [comment]
My experience with my own library (and unfortunately my time) is currently limited.

But I'm currently working on a project that seems similar to yours : it allows the user to arrange widgets in rows and columns, which are drop lists, and those can be nested. It works, but I had to add @mousedown.native.stop="" on drag components to prevent several drags to be initiated at the same time (on leafs and on every draggable parent in the hierarchy because the mousedown events bubble and those events are what initiate a drag). Can you try that fix and tell me if it works any better ?

I've only tested the reordering part so far (widgets, rows and columns can be reordered at any level in the hierarchy). I haven't gotten to the point of re-parenting elements yet. I suspect it will cause further problems.

Here is a gif of the current state of the project :

![ezgif-5-7a6c2f616c8a](https://user-images.githubusercontent.com/35061496/78127675-e1855100-7414-11ea-87b6-92ac83520e8d.gif)

**Comment by Armaldio** [comment]
Wonderful, that worked!

You should add that to a FAQ section on the readme maybe

Many thanks

**Comment by rlemaigre** [comment]
It's a fix that I should add to the library itself I think. Generally preventing mousedown from bubbling on drag components, that is. Not sure if it could cause issues to do that as default...

Please keep me posted about the progress of your work, I'd be very interested to see how it turns out :-)
