### ISSUE TITLE
Disable reorder transition

### ISSUE THREAD

**Issue by Armaldio** [rlemaigre/Easy-DnD#9]
I'd like to disable this behaviour because it's causing some issues
I've tried defining the DropList>reordering-drag-image slot but it seems to have no effects

![TZ4tIFEsFg](https://user-images.githubusercontent.com/3089715/78145315-04256300-7431-11ea-9392-ff22acd123d1.gif)

**Comment by rlemaigre** [comment]
I've set up a playground to try to improve the behavior of nested drop lists. It's App7.vue. Hopefuly I can do something about it...

**Comment by Armaldio** [comment]
Maybe try to provide a way to set our own threshold
Currently it switch directly when it overlap an other object
Switch when threshold > 1/2 of the size of the next element may improve

**Comment by rlemaigre** [comment]
I don't understand. It shouldn't do that. It's as if when you are inserting in the box on the front, the box in the background still think you're reordering its items. That's a bug, only one drop list at a time should be "active", but I can't reproduce it. I've tried to set up the same situation in the project I'm currently working on, but I don't have that problem as you can see below.

![Média1](https://user-images.githubusercontent.com/35061496/78759274-b2745f80-797f-11ea-9d85-ecd2f4f33390.gif)

**Comment by rlemaigre** [comment]
@Armaldio If you're still interested in any of this, I got it working properly I think.

The only limitation is, the visual feedback displayed in between items during the drag must not take any space otherwise proper behavior is not guaranteed. In my tests, I used a div with "flex: 0 0 0; align-self: strech; outline: 1px solid blue". Also, currently nothing prevents a drop list to be dropped into itself or one of its descendants. For now, this must be prevented using the "accepts-data" prop of drop lists.

It is not documented yet. It is published on NPM as 1.5.0. The example is in App7. Key elements are, nested drop lists must now declare whether they are columns or rows by use of the "column" or "row" prop. Both the feedback and reordering-feedback slots must be defined (and take no space as explained above).

![ezgif-6-9037815a1c28](https://user-images.githubusercontent.com/35061496/79257167-8a0dc900-7e89-11ea-8993-b82032d09037.gif)

**Comment by Armaldio** [comment]
Really sweet !
I will try that asap

**Comment by Armaldio** [comment]
I can't find the "reordering-feedback" slot.
I can't find it in the source, it has no effects if I add it. Even the App7 file is not using it like in your example

**Comment by Armaldio** [comment]
Shame on me, the error was on my part
It's working, thanks !

**Comment by rlemaigre** [comment]
@Armaldio Sorry I published version 1.5.0 on NPM but forgot to push the code to github.
