### ISSUE TITLE
in firefox, drop the image open the new tab

### ISSUE THREAD

**Issue by YFAnt** [rlemaigre/Easy-DnD#98]
hello , i use this package in fireFox 95 .when i drop the image , the browser always open  a new tab to show this image. Can i set some config to resolve this problem?

thanks :)

**Comment by nicholaszuccarelli** [comment]
I am going to mark this as closed unless you can provide a codepen example we can use. This sounds unrelated to the package.

**Comment by YFAnt** [comment]
i show this code in  https://codesandbox.io/s/crazy-glade-w1kcz?file=/src/App.vue . in firefox,  the brower occasionally trigger dropevent instead of custom drop events. 
![image](https://user-images.githubusercontent.com/46584057/146285756-f8c0e29c-234c-4d37-8eb4-8fda26ea0ea9.png)

**Comment by YFAnt** [comment]
@nicholaszuccarelli

**Comment by nicholaszuccarelli** [comment]
Thanks. I’ll reopen the issue and if I have a chance I’ll take a look at it :)

**Comment by YFAnt** [comment]
@nicholaszuccarelli   in lib/src/mixins/DragMixin.ts  line 150, You commented out a sentence. I found that opening it can solve the above problems. What was the reason for commenting it at that time？

**Comment by YFAnt** [comment]
![image](https://user-images.githubusercontent.com/46584057/146318909-5b725b20-e66b-4941-a448-da02686d4577.png)

**Comment by nicholaszuccarelli** [comment]
Pull request has been made and is awaiting merge. @rlemaigre

**Comment by nicholaszuccarelli** [comment]
As of the next version, I have had to revert this change because it breaks draggable element interaction.
https://github.com/rlemaigre/Easy-DnD/pull/103

However there is a solution to this problem for the next version.
`<img alt="Vue logo" src="https://vuejs.org/images/logo.png" width="25%" ondragstart="return false;" />`

You need to append `ondragstart="return false;"` to the `img` tag. This will make interaction with images work as expected.
